name: Run Powershell Script

on:
  push:
    branches: [ "main" ]

jobs:
  test-powershell:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run hello.ps1
      shell: pwsh
      run: |
        ./hello.ps1      